import JSZip from 'jszip';
import FileSaver from 'file-saver';

// Helper to generate the file structure for both ZIP and StackBlitz
const getProjectFiles = (code: string) => {
  const files: Record<string, string> = {};

  // 1. package.json
  const packageJson = {
    name: "image2code-project",
    private: true,
    version: "0.0.0",
    type: "module",
    scripts: {
      "dev": "vite",
      "build": "vite build",
      "lint": "eslint . --ext ts,tsx --report-unused-disable-directives --max-warnings 0",
      "preview": "vite preview"
    },
    dependencies: {
      "react": "^18.2.0",
      "react-dom": "^18.2.0",
      "lucide-react": "^0.263.1"
    },
    devDependencies: {
      "@types/react": "^18.2.15",
      "@types/react-dom": "^18.2.7",
      "@vitejs/plugin-react": "^4.0.3",
      "autoprefixer": "^10.4.14",
      "postcss": "^8.4.27",
      "tailwindcss": "^3.3.3",
      "typescript": "^5.0.2",
      "vite": "^4.4.5"
    }
  };
  files["package.json"] = JSON.stringify(packageJson, null, 2);

  // 2. tsconfig.json
  const tsConfig = {
    "compilerOptions": {
      "target": "ES2020",
      "useDefineForClassFields": true,
      "lib": ["ES2020", "DOM", "DOM.Iterable"],
      "module": "ESNext",
      "skipLibCheck": true,
      "moduleResolution": "bundler",
      "allowImportingTsExtensions": true,
      "resolveJsonModule": true,
      "isolatedModules": true,
      "noEmit": true,
      "jsx": "react-jsx",
      "strict": true,
      "noUnusedLocals": true,
      "noUnusedParameters": true,
      "noFallthroughCasesInSwitch": true
    },
    "include": ["src"],
    "references": [{ "path": "./tsconfig.node.json" }]
  };
  files["tsconfig.json"] = JSON.stringify(tsConfig, null, 2);

  // 3. tsconfig.node.json
  const tsConfigNode = {
    "compilerOptions": {
      "composite": true,
      "skipLibCheck": true,
      "module": "ESNext",
      "moduleResolution": "bundler",
      "allowSyntheticDefaultImports": true
    },
    "include": ["vite.config.ts"]
  };
  files["tsconfig.node.json"] = JSON.stringify(tsConfigNode, null, 2);

  // 4. vite.config.ts
  const viteConfig = `
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react()],
})
`;
  files["vite.config.ts"] = viteConfig.trim();

  // 5. tailwind.config.js
  const tailwindConfig = `
/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}
`;
  files["tailwind.config.js"] = tailwindConfig.trim();

  // 6. postcss.config.js
  const postcssConfig = `
export default {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}
`;
  files["postcss.config.js"] = postcssConfig.trim();

  // 7. index.html
  const indexHtml = `
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Image2Code Generated App</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
`;
  files["index.html"] = indexHtml.trim();

  // 8. src/index.css
  const indexCss = `
@tailwind base;
@tailwind components;
@tailwind utilities;
`;
  files["src/index.css"] = indexCss.trim();

  // 9. src/main.tsx
  const mainTsx = `
import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App.tsx'
import './index.css'

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
)
`;
  files["src/main.tsx"] = mainTsx.trim();

  // 10. src/App.tsx
  files["src/App.tsx"] = code;

  // 11. README.md
  const readme = `
# Image2Code Generated Project

This project was generated by Image2Code AI.

## How to run

1. Install dependencies:
   \`\`\`bash
   npm install
   \`\`\`

2. Start the development server:
   \`\`\`bash
   npm run dev
   \`\`\`

3. Build for production:
   \`\`\`bash
   npm run build
   \`\`\`
`;
  files["README.md"] = readme.trim();

  return files;
};

export const downloadProject = async (code: string) => {
  const files = getProjectFiles(code);
  const zip = new JSZip();

  Object.entries(files).forEach(([path, content]) => {
    zip.file(path, content);
  });

  const content = await zip.generateAsync({ type: "blob" });
  FileSaver.saveAs(content, "image2code-project.zip");
};

export const openInStackBlitz = (code: string) => {
  const files = getProjectFiles(code);
  
  const form = document.createElement('form');
  form.method = 'POST';
  form.action = 'https://stackblitz.com/run';
  form.target = '_blank';

  // Add project template
  const templateInput = document.createElement('input');
  templateInput.type = 'hidden';
  templateInput.name = 'project[template]';
  templateInput.value = 'node'; // Vite/React requires the node template
  form.appendChild(templateInput);

  // Add title
  const titleInput = document.createElement('input');
  titleInput.type = 'hidden';
  titleInput.name = 'project[title]';
  titleInput.value = 'Image2Code Generated App';
  form.appendChild(titleInput);

  // Add description
  const descInput = document.createElement('input');
  descInput.type = 'hidden';
  descInput.name = 'project[description]';
  descInput.value = 'Generated by Image2Code AI';
  form.appendChild(descInput);

  // Add files
  Object.entries(files).forEach(([path, content]) => {
    const fileInput = document.createElement('input');
    fileInput.type = 'hidden';
    fileInput.name = `project[files][${path}]`;
    fileInput.value = content;
    form.appendChild(fileInput);
  });

  document.body.appendChild(form);
  form.submit();
  document.body.removeChild(form);
};